#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk-compile-json. You may or may not want to
 * edit it directly.
 */
//#define UNICODE_KEY_WINC KC_RGUI

enum unicode_names {
    LOGICAL_AND,
    LOGICAL_OR,
    UNION,
    INTERSECTION,
    SUBSET,
    SUPERSET,
    FORALL,
    UINFINITY,
    EXISTS,
    PARTIAL_DIFFERENTIAL,
    UP_TACK,
    DOWN_TACK,
    RIGHT_TACK,
    LEFT_TACK,
    UP_ARROW,
    DOWN_ARROW,
    LEFT_ARROW,
    RIGHT_ARROW,
    LEFT_RIGHT_ARROW,
    LAMBDA,
    GAMMA,
    LEFT_FLOOR,
    RIGHT_FLOOR,
    NOT_EQUAL,
    ASYMPTOTICALLY_EQUAL,
    IDENTICAL_TO,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN_OR_EQUAL
};

const uint32_t PROGMEM unicode_map[] = {
    [LOGICAL_AND]           = 0x2227,
    [LOGICAL_OR]            = 0x2228,
    [UNION]                 = 0x222A,
    [INTERSECTION]          = 0x2229,
    [SUBSET]                = 0x2282,
    [SUPERSET]              = 0x2283,
    [FORALL]                = 0x2200,
    [UINFINITY]             = 0x221E,  
    [EXISTS]                = 0x2203,
    [PARTIAL_DIFFERENTIAL]  = 0x2202,
    [UP_TACK]               = 0x22A5,
    [DOWN_TACK]             = 0x22A4,
    [RIGHT_TACK]            = 0x22A2,
    [LEFT_TACK]             = 0x22A3,
    [UP_ARROW]              = 0x2191,
    [DOWN_ARROW]            = 0x2193,
    [LEFT_ARROW]            = 0x2190,
    [RIGHT_ARROW]           = 0x2192,
    [LEFT_RIGHT_ARROW]      = 0x2194,
    [LAMBDA]                = 0x03BB,
    [GAMMA]                 = 0x0393,
    [LEFT_FLOOR]            = 0x230A,
    [RIGHT_FLOOR]           = 0x2308,
    [NOT_EQUAL]             = 0x2260,
    [ASYMPTOTICALLY_EQUAL]  = 0x2243,
    [IDENTICAL_TO]          = 0x2261,
    [LESS_THAN_OR_EQUAL]    = 0x2264,
    [GREATER_THAN_OR_EQUAL] = 0x2265,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT(   KC_ESC,     KC_F1,              KC_F2,          KC_F3,          KC_F4,              KC_F5,                      KC_F6,              KC_F7,                  KC_F8,                      KC_F9,                  KC_F10,                     KC_F11,     KC_F12,     KC_DEL,     KC_CALC,    KC_PSCR,    KC_TRNS,    KC_TRNS, \
                        KC_GRV,     KC_1,               KC_2,           KC_3,           KC_4,               KC_5,                       KC_6,               KC_7,                   KC_8,                       KC_9,                   KC_0,                       KC_MINS,    KC_EQL,     KC_BSPC,    KC_PSLS,    KC_PAST,    KC_PMNS,    KC_PPLS, \
                        KC_TAB,     KC_Q,               KC_W,           KC_E,           KC_R,               KC_T,                       KC_Y,               KC_U,                   KC_I,                       KC_O,                   KC_P,                       KC_LBRC,    KC_RBRC,    KC_BSLS,    KC_PGUP,    KC_P7,      KC_P8,      KC_P9, \
                        KC_CAPS,    KC_A,               KC_S,           KC_D,           KC_F,               KC_G,                       KC_H,               KC_J,                   KC_K,                       KC_L,                   KC_SCLN,                    KC_QUOT,    KC_ENT,     KC_ENT,     KC_PGDN,    KC_P4,      KC_P5,      KC_P6, \
                        KC_LSFT,    KC_LSFT,            KC_Z,           KC_X,           KC_C,               KC_V,                       KC_B,               KC_N,                   KC_M,                       KC_COMM,                KC_DOT,                     KC_SLSH,    KC_RSFT,    KC_UP,      KC_SLSH,    KC_P1,      KC_P2,      KC_P3, \
                        KC_LCTL,    KC_LGUI,            KC_LALT,        MO(1),          KC_SPC,             KC_SPC,                     KC_SPC,             KC_SPC,                 KC_RALT,                    KC_RGUI,                MO(1),                      KC_RCTL,    KC_LEFT,    KC_DOWN,    KC_RGHT,    KC_P0,      KC_PDOT,    KC_PENT),

        [1] = LAYOUT(   KC_TRNS,    KC_TRNS,            KC_TRNS,        KC_TRNS,        KC_TRNS,            KC_TRNS,                    KC_TRNS,            KC_TRNS,                KC_TRNS,                    KC_TRNS,                KC_TRNS,                    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_NLCK,    KC_TRNS,    KC_TRNS,    KC_TRNS, \
                        KC_TRNS,    KC_TRNS,            KC_TRNS,        KC_TRNS,        KC_TRNS,            KC_TRNS,                    KC_TRNS,            KC_TRNS,                KC_TRNS,                    KC_TRNS,                KC_TRNS,                    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS, \
                        KC_TRNS,    X(LOGICAL_AND),     X(LOGICAL_OR),  X(UNION),       X(INTERSECTION),    X(SUBSET),                  X(SUPERSET),        X(FORALL),              X(UINFINITY),               X(EXISTS),              X(PARTIAL_DIFFERENTIAL),    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_VOLU,    KC_TRNS,    KC_TRNS,    KC_TRNS, \
                        KC_TRNS,    X(UP_TACK),         X(DOWN_TACK),   X(RIGHT_TACK),  X(LEFT_TACK),       X(UP_ARROW),                X(DOWN_ARROW),      X(LEFT_ARROW),          X(RIGHT_ARROW),             X(LEFT_RIGHT_ARROW),    KC_TRNS,                    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_VOLD,    KC_TRNS,    KC_TRNS,    KC_TRNS, \
                        KC_TRNS,    KC_TRNS,            X(LAMBDA),      X(GAMMA),       X(NOT_EQUAL),       X(ASYMPTOTICALLY_EQUAL),    X(IDENTICAL_TO),    X(LESS_THAN_OR_EQUAL),  X(GREATER_THAN_OR_EQUAL),   KC_TRNS,                KC_TRNS,                    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_MUTE,    KC_TRNS,    KC_TRNS,    KC_TRNS, \
                        KC_TRNS,    KC_TRNS,            KC_TRNS,        KC_TRNS,        KC_TRNS,            KC_TRNS,                    KC_TRNS,            KC_TRNS,                KC_TRNS,                    KC_TRNS,                KC_TRNS,                    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS)
};


void matrix_init_user(void) {
    set_unicode_input_mode(UC_WINC);
}